# CircleCI configuration file
version: 2.1

orbs: 
  android: circleci/android@2.1.2
  codecov: codecov/codecov@3.2.3

jobs:
  # Job one with a unique name
  emulator setup:
    docker:
     - image: cimg/base:2022.05
     
    steps:
      - run: echo "Say hello to YAML!"

      - checkout

      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: chmod permissions
          command: ./gradlew clean build

      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results
            
      - codecov/upload

workflows:
  # Name of workflow
  TestsTest:
    # List of jobs that will run
    jobs:
      - emulator setup